- name: manage kubernetes applications
  kpm:
    namespace: "{{item.namespace | default(kpm_namespace | default('default'))}}"
    registry: "{{item.registry | default(kpm_registry | default('https://api.kpm.sh'))}}"
    state: "{{item.state | default(omit)}}"
    version: "{{item.version | default(omit)}}"
    name: "{{item.name}}"
  with_items: "{{kpm_packages}}"
  register: kpmresults
