- name: install kpm
  pip: name=kpm state=latest

- name: manage kubernetes applications
  kpm:
    namespace: "{{item.namespace | default(kpm_namespace | default('default'))}}"
    registry: "{{item.registry | default(kpm_registry | default('https://api.kpm.sh'))}}"
    state: "{{item.state | default(omit)}}"
    version: "{{item.version | default(omit)}}"
    variables: "{{item.variables | default(omit)}}"
    name: "{{item.name}}"
  with_items: "{{kpm_packages}}"
  register: kpmresults
